pingcap/kvproto

- proto/raft_cmdpb.proto
These comments are obsolete since the `split_key` must be specified.
> proto/raft_cmdpb: remove obsolete comments

- circle.yml
currently ci failed with:
```
Compiling grpcio v0.1.1
$<2>error$<2>$<2>: use of unstable library feature 'thread_id' (see issue #21507)$<2>
$<2>$<2>--> $<2>/home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-0.1.1/src/async/executor.rs:16:25$<2>
$<2>$<2>|$<2>
$<2>16$<2> $<2>$<2>| $<2>use std::thread::{self, ThreadId};$<2>
$<2>$<2>| $<2>                        $<2>$<2>^^^^^^^^$<2>
$<2>$<2>|$<2>
$<2>$<2>= $<2>$<2>help$<2>: add #![feature(thread_id)] to the crate attributes to enable$<2>
$<2>error$<2>$<2>: use of unstable library feature 'thread_id' (see issue #21507)$<2>
$<2>$<2>--> $<2>/home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-0.1.1/src/cq.rs:17:5$<2>
$<2>$<2>|$<2>
$<2>17$<2> $<2>$<2>| $<2>use …
```
> update circleci rustc version

- .gitattributes
Previous PR is https://github.com/pingcap/kvproto/pull/260  but it is not working.
According to [git-scm](https://git-scm.com/docs/gitattributes), we may need to replace directories with `foo/**` style. Hope it works.
@Hoverbear PTAL
> Fix .gitattribute

- common.sh
Currently we're not strict enough checking versions. I have protoc 3.6.1 and it passes the check, despite generating thousands of changes on `master`.
> Fix the version check.

- Makefile
Signed-off-by: AndreMouche <AndreMouche@126.com>
Hi,
This PR will fix the command `make rust` which is used to generate code for rust.
@overvenus @hicqu PTAL
> Makefile: fix make rust

- pkg/coprocessor/coprocessor.pb.go
- pkg/debugpb/debugpb.pb.go
- pkg/errorpb/errorpb.pb.go
- pkg/import_kvpb/import_kvpb.pb.go
- pkg/import_sstpb/import_sstpb.pb.go
- pkg/kvrpcpb/kvrpcpb.pb.go
- pkg/metapb/metapb.pb.go
- pkg/pdpb/pdpb.pb.go
- pkg/raft_cmdpb/raft_cmdpb.pb.go
- pkg/raft_serverpb/raft_serverpb.pb.go
- pkg/tikvpb/tikvpb.pb.go
- src/protobuf/coprocessor.rs
- src/protobuf/debugpb.rs
- src/protobuf/errorpb.rs
- src/protobuf/import_kvpb.rs
- src/protobuf/import_sstpb.rs
- src/protobuf/kvrpcpb.rs
- src/protobuf/metapb.rs
- src/protobuf/pdpb.rs
- src/protobuf/raft_cmdpb.rs
- src/protobuf/raft_serverpb.rs
- src/protobuf/tikvpb.rs
This reverts commit c982a6770367b4106c17bc454159180e9853f35b.
Custom debug requires descriptor, we need to think of another way to fix it.
> Revert "Make debug format pretty again (#377)"

- Cargo.toml
Since we yanked 0.4.1, kvproto would not build because it would try to pull 0.4.2 which lacks Prost support. This change points to a specific git commit which includes Prost support
> Fix the build by using a specific git commit for raft

- pkg/kvrpcpb/kvrpcpb.pb.go
- proto/kvrpcpb.proto
- src/prost/kvrpcpb.rs
- src/prost/wrapper_kvrpcpb.rs
- `Deadlock` key error will be used for pessimistic transaction single statement rollback.
- `for_update_ts` in `PrewriteRequest`  will be used to check if a conflict lock is already committed.
> add Deadlock Key error and for_update_ts in Prewrite

- Makefile
Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>
grep doesn't support -z option in mac OS.
> fix mac make

- src/protobuf/import_sstpb.rs
- src/protobuf/import_sstpb_grpc.rs
- src/protobuf/pdpb.rs
4.x uses Prost so the *.rs files are gone. But on 3.x we still need them 🤦.
> import_sstpb,pdpb: update the Rust interface

- README.md
- src/protobuf/kvrpcpb.rs
generate .rs file for #565 in 3.0
.... in master we no need `make rust` in kvproto and autogenerate when tikv compile, but for 3.0 still need `make rust`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/kvproto/571)
> txn: generate check_not_exists op in rust

- .gitignore
- Cargo.toml
kvproto#631 blocks other PR to update kvproto. Let's merge it after other components have been updated.
> Revert "upgrade dependencies"

- src/protobuf/backup.rs
Add missing changes in #648. Seems branch `release-3.1` is different for `release-4.0` and `master`. And The tests for `release-3.1` does check if there are any change after `make build`
> fix for auto-cherry-pick #648

- Cargo.toml
This change is needed to make sure the compatibility with newer libstdc++
shipped together with GCC 11.
Signed-off-by: Schrodinger ZHU Yifan <i@zhuyi.fan>
> dep(grpcio): upgrade to 0.9.0

- proto/kvrpcpb.proto
Issue Number：close #784
1. add a flag used by tidb to tell tikv which operation can be allowed when tikv disk full happens.
not available
not available
> add `allowed_on_disk_full` field for message Context

- pkg/pdpb/pdpb.pb.go
- proto/pdpb.proto
This reverts commit 3329b3c5404ce72aeff745d10e77562e56d0983b. since it's not used in release-5.4
> Revert "`GlobalConfig` Rule them all (#828)" in release-5.4

- cpp/CMakeLists.txt
Signed-off-by: JaySon-Huang <tshent@qq.com>
Problem Summary:
In https://github.com/pingcap/kvproto/pull/955, we generate the .pb.h, .pb.cc files under "${CMAKE_CURRENT_BINARY_DIR}/kvproto", and also set the include path to it. That's not right because we include headers by using `#include <kvproto/coprocessor.pb.h>` in C++ code.
Ref https://github.com/pingcap/tipb/pull/273
> Fix cpp include header path

- .github/workflows/cpp-test.yaml
- .gitignore
- cpp/CMakeLists.txt
- cpp/cmake/find_abseil-cpp.cmake
Signed-off-by: JaySon-Huang <tshent@qq.com>
The header files of grpc depends on absl library since some version.
Build error: https://ci.pingcap.net/blue/organizations/jenkins/tiflash-build-common/detail/tiflash-build-common/11206/pipeline/
Ref: https://github.com/grpc/grpc/pull/26802
> Upgrade C++ grpc version to 1.44

- proto/kvrpcpb.proto
ref https://github.com/pingcap/tidb/issues/38587
> add `txn_source` in kv context

- pkg/coprocessor/coprocessor.pb.go
- proto/coprocessor.proto
Signed-off-by: cfzjywxk <lsswxrxr@163.com>
Ref: https://github.com/pingcap/tidb/issues/39361
Ref(RFC): https://github.com/pingcap/tidb/pull/39362 
`task_id` is to record the task index, I'm not quite sure if it's necessary for the client to process the responses.
> cop: support batch coprocessor for tikv

- Dockerfile
I meet the following error: 
```
Cannot load io/fs: malformed module path "io/fs": missing dot in first path element
```
Due to the version of go is `1.13` which is two low, update to `1.18.2`
> update go version to `1.18.2` in docker

- Cargo.toml
ditto https://github.com/tikv/protobuf-build/pull/65
Otherwise build TiKV would fail due to:
```
error: failed to run custom build command for `kvproto v0.0.2 (https://github.com/pingcap/kvproto.git#b8e6dcdd)`
Caused by:
process didn't exit successfully: `/Users/tison/Brittani/tikv/target/debug/build/kvproto-22216c28e5c399d1/build-script-build` (exit status: 101)
--- stderr
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/tison/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-build-0.13.0/src/protobuf_impl.rs:48:71
stack backtrace:
0: rust_begin_unwind
at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:575:5
1: core::panicking::panic_fmt
at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:65:14 …
```
> build: update protobuf-build for newer protoc

- proto/raft_serverpb.proto
- scripts/proto.lock
Related issue: https://github.com/tikv/tikv/issues/15972
This commit adds two new new ExtraMessage types that are part of the snapshot
gen precheck process: Before a leader generates a snapshot, it sends a precheck
request to the target follower. The follower responds with a boolean value
indicating whether the check succeeds.
> raft_serverpb: add new ExtraMessage types for the snapshot gen precheck process

- .github/workflows/cpp-test.yaml
- .github/workflows/rust-test.yaml
- src/lib.rs
For now test/cpp and test/rust cannot pass due to `llvm` and `gcc` are updated.
> Lock Ubuntu at 22.04 for CPP / Rust Test Workflow

- pkg/configpb/configpb.pb.gw.go
Revert unnecessary changes to configpb introduced by https://github.com/pingcap/kvproto/pull/1291/files#diff-778439458ab010b5d2a619d82819b3a0a5b7bb2c117c3e7b4fdbf9aa0c2fb80cL23, built `go` deps with lower version on MacOS.
> configpb: revert changes to configpb as building with lower go version.
