pingcap/kvproto

pkg/util/codec.go, pkg/util/codec_test.go
=> [DNM]pkg/kvrpc: add message codec package.

generate_rust.sh, src/coprocessor.rs, src/errorpb.rs, src/kvrpcpb.rs, src/lib.rs, src/metapb.rs, src/msgpb.rs, src/mvccpb.rs, src/pd_jobpb.rs, src/pdpb.rs, src/raft_cmdpb.rs, src/raft_serverpb.rs, src/raftpb.rs
@ngaut @BusyJay @disksing @tiancaiamao
=> *: use protocbuf 1.0.20

Cargo.lock, Cargo.toml, generate_rust.sh
@ngaut @siddontang @disksing @zhangjinpeng1987 PTAL
=> upgrade proto to 1.0.23

pkg/coprocessor/coprocessor.pb.go, pkg/eraftpb/eraftpb.pb.go, pkg/errorpb/errorpb.pb.go, pkg/kvrpcpb/kvrpcpb.pb.go, pkg/metapb/metapb.pb.go, pkg/msgpb/msgpb.pb.go, pkg/mvccpb/mvccpb.pb.go, pkg/pdpb/pdpb.pb.go, pkg/raft_cmdpb/raft_cmdpb.pb.go, pkg/raft_serverpb/raft_serverpb.pb.go
=> *: update proto.

generate_rust.sh
install rust-protobuf and gogoproto if missing when make rust
=> script: add dependencies to make rust

Cargo.lock, Cargo.toml, src/coprocessor.rs, src/eraftpb.rs, src/errorpb.rs, src/kvrpcpb.rs, src/metapb.rs, src/msgpb.rs, src/mvccpb.rs, src/pdpb.rs, src/raft_cmdpb.rs, src/raft_serverpb.rs
=> use protobuf 1.2.1

Makefile, circle.yml, pkg/util/codec_test.go
=> *: add cycle.yml

proto/coprocessor.proto, proto/eraftpb.proto, proto/errorpb.proto, proto/kvrpcpb.proto, proto/metapb.proto, proto/pdpb.proto, proto/raft_cmdpb.proto, proto/raft_serverpb.proto, proto/tikvpb.proto
=> *: add java package

LICENSE
Fixes #240.
Uses the license copied from TiKV.
=> *: Add LICENSE

README.md
=> Give the README more content

go.mod, include/google/protobuf/any.proto, include/google/protobuf/api.proto, include/google/protobuf/compiler/plugin.proto, include/google/protobuf/descriptor.proto, include/google/protobuf/duration.proto, include/google/protobuf/empty.proto, include/google/protobuf/field_mask.proto, include/google/protobuf/source_context.proto, include/google/protobuf/struct.proto, include/google/protobuf/timestamp.proto, include/google/protobuf/type.proto, include/google/protobuf/wrappers.proto
Signed-off-by: disksing <i@disksing.com>
To make it work when user does not place proto files in include path.
=> *: vendor proto files

pkg/coprocessor/coprocessor.pb.go, pkg/debugpb/debugpb.pb.go, pkg/errorpb/errorpb.pb.go, pkg/import_kvpb/import_kvpb.pb.go, pkg/import_sstpb/import_sstpb.pb.go, pkg/kvrpcpb/kvrpcpb.pb.go, pkg/metapb/metapb.pb.go, pkg/pdpb/pdpb.pb.go, pkg/raft_cmdpb/raft_cmdpb.pb.go, pkg/raft_serverpb/raft_serverpb.pb.go, pkg/tikvpb/tikvpb.pb.go, proto/pdpb.proto, src/protobuf/pdpb.rs, src/protobuf/pdpb_grpc.rs
- Add get operator service.
- GetStoreResponse add status.
=> *: add get operator service

pkg/coprocessor/coprocessor.pb.go, pkg/debugpb/debugpb.pb.go, pkg/errorpb/errorpb.pb.go, pkg/import_kvpb/import_kvpb.pb.go, pkg/import_sstpb/import_sstpb.pb.go, pkg/kvrpcpb/kvrpcpb.pb.go, pkg/metapb/metapb.pb.go, pkg/pdpb/pdpb.pb.go, pkg/raft_cmdpb/raft_cmdpb.pb.go, pkg/raft_serverpb/raft_serverpb.pb.go, pkg/tikvpb/tikvpb.pb.go, src/protobuf/coprocessor.rs, src/protobuf/debugpb.rs, src/protobuf/errorpb.rs, src/protobuf/import_kvpb.rs, src/protobuf/import_sstpb.rs, src/protobuf/kvrpcpb.rs, src/protobuf/metapb.rs, src/protobuf/pdpb.rs, src/protobuf/raft_cmdpb.rs, src/protobuf/raft_serverpb.rs, src/protobuf/tikvpb.rs
Bring back the pretty print of struct, raw debug format seems annoy everyone.
=> make debug format pretty again

src/prost.rs, src/prost/deadlockpb.rs, src/prost/enginepb.rs, src/prost/kvrpcpb.rs, src/prost/pdpb.rs, src/prost/raft_cmdpb.rs, src/prost/tikvpb.rs, src/prost/wrapper_deadlockpb.rs, src/prost/wrapper_enginepb.rs, src/prost/wrapper_kvrpcpb.rs, src/prost/wrapper_pdpb.rs, src/prost/wrapper_raft_cmdpb.rs
Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>
=> gen rust code for pessimistic lock

pkg/coprocessor/coprocessor.pb.go, pkg/deadlock/deadlock.pb.go, pkg/debugpb/debugpb.pb.go, pkg/enginepb/enginepb.pb.go, pkg/eraftpb/eraftpb.pb.go, pkg/errorpb/errorpb.pb.go, pkg/import_kvpb/import_kvpb.pb.go, pkg/import_sstpb/import_sstpb.pb.go, pkg/kvrpcpb/kvrpcpb.pb.go, pkg/metapb/metapb.pb.go, pkg/pdpb/pdpb.pb.go, pkg/raft_cmdpb/raft_cmdpb.pb.go, pkg/raft_serverpb/raft_serverpb.pb.go, pkg/tikvpb/tikvpb.pb.go, proto/kvrpcpb.proto, src/protobuf/kvrpcpb.rs
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>
=> [cherry-pick] add Deadlock Key error and for_update_ts in Prewrite

Cargo.toml, src/text.rs
Use hex output for all kind of bytes.
=> Pretty print bytes

Cargo.toml
cc https://github.com/tikv/tikv/issues/4864
PTAL @AndreMouche @siddontang
=> Relax the required protobuf version

Cargo.toml, build.rs
This makes no change to the generated code.
PTAL @BusyJay @overvenus
=> Use the new builder API from protobuf-build

pkg/backup/backup.pb.go, pkg/coprocessor/coprocessor.pb.go, pkg/deadlock/deadlock.pb.go, pkg/debugpb/debugpb.pb.go, pkg/enginepb/enginepb.pb.go, pkg/eraftpb/eraftpb.pb.go, pkg/errorpb/errorpb.pb.go, pkg/import_kvpb/import_kvpb.pb.go, pkg/import_sstpb/import_sstpb.pb.go, pkg/kvrpcpb/kvrpcpb.pb.go, pkg/metapb/metapb.pb.go, pkg/pdpb/pdpb.pb.go, pkg/raft_cmdpb/raft_cmdpb.pb.go, pkg/raft_serverpb/raft_serverpb.pb.go, pkg/tikvpb/tikvpb.pb.go, proto/import_kvpb.proto
Signed-off-by: 5kbpers <tangminghua@pingcap.com>
=> import_kvpd: add import_file rpc

src/protobuf/backup.rs
Signed-off-by: linning <linningde25@gmail.com>
=> pick 467 rust code

src/protobuf/kvrpcpb.rs
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>
=> *: generate rust code for lock wait timeout

Cargo.toml
=> Fix broken Rust build by pinning the replace rev

pkg/backup/backup.pb.go, proto/backup.proto
SSE configures the server-side encryption algorithm used when storing this object in S3 and the type should be string.
=> backup: update sse to string

Cargo.toml
Signed-off-by: 5kbpers <tangminghua@pingcap.com>
Update: protobuf-build => 0.11.0, prost => 0.6.0, raft-proto => master, grpcio => 0.5.0
=> Cargo.toml: update dependencies

src/protobuf/kvrpcpb.rs
cherry-pick https://github.com/pingcap/kvproto/pull/571 to 3.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/kvproto/577)
=> txn: generate check_not_exists op in rust

proto/raft_serverpb.proto
Unmerged paths:
(use "git add <file>..." to mark resolution)
both modified:   pkg/coprocessor/coprocessor.pb.go
both modified:   pkg/import_sstpb/import_sstpb.pb.go
both modified:   pkg/metapb/metapb.pb.go
both modified:   pkg/pdpb/pdpb.pb.go
=> Merge release-3.0 into release-3.1

pkg/kvrpcpb/kvrpcpb.pb.go, pkg/tikvpb/tikvpb.pb.go, proto/kvrpcpb.proto, proto/tikvpb.proto
Moves around the messages in kvproto.md (second commit) and improves documentation (first and third commits). There are no material changes to any protos.
PTAL @overvenus @hicqu
=> Add some documentation to the kv protos

pkg/import_sstpb/import_sstpb.pb.go, proto/import_sstpb.proto
cherry-pick #602 to release-4.0
=> sst_importer: add write streaming request (#602)

.gitignore, Cargo.toml
Bump `futures` to 0.3 and `grpcio` to 0.6.
This should fix #630.
=> upgrade dependencies

Cargo.toml
rollback protobuf-codec version change in #647
=> rollback protobuf-codec to 0.11

pkg/kvrpcpb/kvrpcpb.pb.go, proto/kvrpcpb.proto
A command for async commit for checking locks and leaving a rollback tombstone if the lock has not got a success status.
PTAL @sticnarf @cfzjywxk
=> Add a CheckSecondaryLocks message

pkg/errorpb/errorpb.pb.go, proto/errorpb.proto
cherry-pick #694 
---
https://github.com/pingcap/br/issues/606
Add ReadIndexNotReady and ProposalInMergingMode error for the retry of BR.
=> Add ReadIndexNotReady and ProposalInMergingMode error (#694)

.github/workflows/golang-test.yaml, .github/workflows/rust-test.yaml
Signed-off-by: JmPotato <ghzpotato@gmail.com>
=> Refine the Github Actions config

pkg/kvrpcpb/kvrpcpb.pb.go, proto/kvrpcpb.proto
Signed-off-by: Andy Lok <andylokandy@hotmail.com>
=> Fix RawCASResponse.succeed to bool

pkg/tikvpb/tikvpb.pb.go, proto/tikvpb.proto
Signed-off-by: Zhenchi <zhongzc_arch@outlook.com>
Issues: https://github.com/tikv/tikv/issues/10002
=> Clean up verkv

pkg/resource_usage_agent/resource_usage_agent.pb.go, proto/resource_usage_agent.proto
Signed-off-by: Zhenchi <zhongzc_arch@outlook.com>
=> resource_usage: rename

pkg/pdpb/pdpb.pb.go, proto/pdpb.proto
This is part of work tikv/pd#4445.
Signed-off-by: p4tr1ck <patricknicholas@foxmail.com>
=> pdpb: update RegionHeartbeatResponse comments

proto/tracepb.proto
Signed-off-by: Peng Guanwen <pg999w@outlook.com>
=> Use custom java package in tracepb

scripts/common.sh
Signed-off-by: disksing <i@disksing.com>
Fix https://github.com/pingcap/kvproto/issues/874
=> scripts: improve sed version detect

.github/workflows/cpp-test.yaml, .github/workflows/golang-test.yaml, .github/workflows/rust-test.yaml
Signed-off-by: disksing <i@disksing.com>
=> update workflow for release-6.0 (#891)

.github/workflows/rust-test.yaml
Signed-off-by: hillium <yujuncen@pingcap.com>
Because `prost-build` doesn't deliver with protoc more, we need to setup protoc manually.
=> try fix rust build

Cargo.toml
Signed-off-by: tabokie <xy.tao@outlook.com>
For https://github.com/tikv/grpc-rs/pull/597
=> update grpc to 0.10.4

Makefile, go.mod, go.sum, pkg/configpb/configpb.pb.gw.go, pkg/kvrpcpb/kvrpcpb.pb.go, pkg/tracepb/tracepb.pb.go, scripts/generate_go.sh, tools.go
Abandon retool because it has been deprecated.
=> use go module to manage tools version

pkg/schedulingpb/schedulingpb.pb.go, proto/schedulingpb.proto, scripts/proto.lock
See https://github.com/tikv/pd/pull/6976
=> Support forwarding store request

pkg/logbackuppb/logbackuppb.pb.go, proto/logbackuppb.proto, scripts/proto.lock
=> added force flush for log backup

OWNERS, OWNERS_ALIASES, proto/OWNERS
Update OWNERS file
relate to PR  https://github.com/pingcap/kvproto/pull/1302
=> [skip ci] Update OWNERS file
